name: "Default Menu"
size: 45
frame-item: BLACK_STAINED_GLASS_PANE
items:
  item-22:
    material: APPLE
    name: "Apples"
    lore:
      - "Press this item to"
      - "get 12 apples"
    commands:
      - give {player} apple 12
  item-0:
    material: BARRIER
    name: "Close Menu"

